### ISSUE TITLE
helm-execute-persistent-action in various helm commands (find/locate/mini/find-files)

### ISSUE THREAD

**Issue by issue-dispenser** [emacs-helm/helm#1253]
* In `helm-find` and `helm-locate`, I believe doing two consecutive `helm-execute-persistent-action`'s should kill the buffer that was being previewed (similar to what happens when one gives a prefix argument to `helm-execute-persistent-action` in `helm-find-files`). It currently does nothing.

* It would be very nice if doing two consecutive `helm-execute-persistent-action`'s in `helm-mini` would close (but not kill) the buffer that is being previewed. Currently it does nothing.

* Giving a prefix argument to `helm-execute-persistent-action` in `helm-mini` is not only undocumented in `helm-mini`'s interface, but also it saves the buffer being killed without asking. I believe that it should display an additional prompt asking if the buffer should be saved or not (or just act as if you killed it with `M-D` and don't write at all, which seems more consistent).

* Giving a prefix argument to `helm-execute-persistent-action` in `helm-find-files` does not kill/close the previewed buffer if said buffer was followed from a symlink. I believe it should, if possible.

**Comment by thierryvolpiatto** [comment]
I think all issues have been fixed here, except the last (symlink) but I wont fix it, it is ok for me as it is actually.

**Comment by issue-dispenser** [comment]
helm-buffers-list/mini still doesn't mention the prefix argument but other than that and the symlink deal it's been fixed.

**Comment by thierryvolpiatto** [comment]
issue-dispenser <notifications@github.com> writes:

> helm-buffers-list/mini still doesn't mention the prefix argument

You mean the prefix arg to kill buffer ? (i.e C-u C-j)

Perhaps it's time to drop it (no more prefix arg for this) now we have
C-c d.

-- 
Thierry
https://emacs-helm.github.io/helm/
