### ISSUE TITLE
Put selected files to a (w)dired buffer (for batch renaming!)

### ISSUE THREAD

**Issue by Ambrevar** [emacs-helm/helm#1783]
I have a feature request, assuming that is not possible already.

Add the selection of `helm-find` or `helm-find-files` to a dired buffer, in a fashion similar to `find-dired` or `find-name-dired`. This would enable us to batch-rename any selection of files using `wdired`.

How cool is that?! :)

**Comment by thierryvolpiatto** [comment]
Pierre Neidhardt <notifications@github.com> writes:

> I have a feature request, assuming that is not possible already.
>
> Add the seletion of helm-find or helm-find-files to a dired buffer, in
> a fashion similar to find-dired or find-name-dired. This would enable
> us to batch-rename any selection of files using wdired.

You can already rename your files from helm-find-files with M-% (see
documentation in C-h m).

See also the serial rename actions.

Of course your proposition would allow editing with iedit, which would
be cool indeed.

--
Thierry
Gpg Key fingerprint = 6CEC 7081 AB33 E251 4AB8  5FC2 28D1 7F53 59F2 9997

**Comment by Ambrevar** [comment]
I know, but the point is twofolds:

1. To _find_ the files with helm which is so much more convenient.
2. To edit them with powerful tools, e.g. iedit as you suggested, multi-cursors, you name it.

**Comment by thierryvolpiatto** [comment]
I meant M-% from helm-find-files not from wdired.

**Comment by Ambrevar** [comment]
Oh, right, I am aware of that too, but this does not allow for individual and more generic editing of file names.

**Comment by Ambrevar** [comment]
Thanks for the change. There seems to be some issues however:

- Using wdired to modify some file names but not all, when applying the changes Emacs asks "File XXX already exists; rename to it anyway?" for the files that were not renamed. Is there any way to overcome that?

- I'm left with an empty dired buffer, or a buffer with a random subset of the selected files. I can't see the logic here.

- On second try, if the *Find* buffer was not killed, it will be poped up, empty.

**Comment by thierryvolpiatto** [comment]
Pierre Neidhardt <notifications@github.com> writes:

> Thanks for the change. There seems to be some issues however:
>
>   * Using wdired to modify some file names but not all, when applying
>     the changes Emacs asks "File XXX already exists; rename to it
>     anyway?" for the files that were not renamed. Is there any way to
>     overcome that?

No, this is up to you to rename file with a name that do not clash with
existing fnames, this is wdired not helm so I can't do much on this.
M-% from helm-find-files is handling this renaming files with foo(1).txt
for example.

>   * I'm left with an empty dired buffer, or a buffer with a random
>   subset of the selected files. I can't see the logic here.

I don't see how you can endup with an empty buffer here, the code is
quite simple and should not fail there.

From helm-find-files, mark some files then hit C-x C-q, you should have
the marked files in the dired buffer.

>   * On second try, if the Find buffer was not killed, it will be poped up, empty.

Hmm, not sure how you launched this new function.

Please describe exactly what you are doing step by step.

Thanks.

--
Thierry
Gpg Key fingerprint = 6CEC 7081 AB33 E251 4AB8  5FC2 28D1 7F53 59F2 9997

**Comment by thierryvolpiatto** [comment]
1) Mark some files from helm-find-files

![capture d ecran_2017-06-08_21-38-02](https://user-images.githubusercontent.com/1533939/26947454-0b76840e-4c93-11e7-9d46-591ab9265e0d.png)

2) Hit C-x C-q (with C-u start wdired)

![capture d ecran_2017-06-08_21-38-43](https://user-images.githubusercontent.com/1533939/26947480-2d131636-4c93-11e7-93c7-ef5e85ba5b72.png)

**Comment by Ambrevar** [comment]
- Start `emacs -Q`, load helm.
- `helm-find-files`
- Mark 2 or more files.
- `C-u C-x C-q`
- Modify one file name.
- `C-x C-q`
- When asked, confirm the changes.
- Wdired ask for confirmation about non-renamed files (this does not happen with `find-name-dired`).
- I'm left with an empty `*Find*` buffer, which also happens with `find-name-dired`.
- If I repeat the above from step 2 (`helm-find-files`) while a *Find* buffer is open (either from before or from another call to `find-name-dired`), the `*Find*` buffer is unburied but left unchanged.

**Comment by Ambrevar** [comment]
By the way, there is another good reason not to use `wdired` with `find-name-dired`: it calls the `-ls` parameter of GNU find which _shell-escapes_ the file names, thus making it very unpractical for `wdired` since all the escapes have to be removed first.

**Comment by thierryvolpiatto** [comment]
Pierre Neidhardt <notifications@github.com> writes:

>   * Start emacs -Q, load helm.

You can use ./emacs-helm.sh instead.

>   * helm-find-files
>   * Mark 2 or more files.
>   * C-u C-x C-q
>   * Modify one file name.

From here all what you are doing is no more helm related.

>   * C-x C-q

Why this C-x C-q ?

>   * When asked, confirm the changes.

Good.

>   * Wdired ask for confirmation about non-renamed files (this does not
>   happen with find-name-dired).

Please keep focus on starting with helm-find-files, you lost me with
find-name-dired, why is it involved here ?

>   * I'm left with an empty *Find* buffer, which also happens with
>   find-name-dired.

Why a *Find* buffer ?

You lost me again here.

>   * If I repeat the above from step 2 (helm-find-files) while a Find
>     buffer is open (either from before or from another call to
>     find-name-dired), the *Find* buffer is unburied but left
>     unchanged.

Yes if a dired buffer exists - I assume *Find* is a dired buffer - 
it will not be overwrited, you have to kill it before (or after each use).

So for my concern (helm part) seems everything is working fine, all the
problems you describe are related to usage of wdired outside helm.

I think editing file names with wdired can be good sometimes (when using
e.g iedit is needed), but in most conditions, you have better time to
use M-% from helm-find-files which is more powerful for renaming, its
only limitation is it works only in same directory (but generally it is
what most people want) and on basename (BTW).

--
Thierry
Gpg Key fingerprint = 6CEC 7081 AB33 E251 4AB8  5FC2 28D1 7F53 59F2 9997

**Comment by thierryvolpiatto** [comment]
Pierre Neidhardt <notifications@github.com> writes:

> By the way, there is another good reason not to use wdired with
> find-name-dired: it calls the -ls parameter of GNU find which
> shell-escapes the file names, thus making it very unpractical for
> wdired since all the escapes have to be removed first.

Please do not use find-name-dired but C-c / from helm-find-files, I will
add an open a dired buffer with marked files soon.

Let focus with only helm-find-files + C-x C-q for now.

Thanks.

--
Thierry
Gpg Key fingerprint = 6CEC 7081 AB33 E251 4AB8  5FC2 28D1 7F53 59F2 9997

**Comment by thierryvolpiatto** [comment]
Pierre Neidhardt <notifications@github.com> writes:

> By the way, there is another good reason not to use wdired with
> find-name-dired: it calls the -ls parameter of GNU find which
> shell-escapes the file names, thus making it very unpractical for
> wdired since all the escapes have to be removed first.

I will try to debug further more but it seems wdired is not able to
handle files coming from differents directories, it seems it is based on
default-directory and no more.
If it was the case I will remove for now this new feature.

--
Thierry
Gpg Key fingerprint = 6CEC 7081 AB33 E251 4AB8  5FC2 28D1 7F53 59F2 9997

**Comment by thierryvolpiatto** [comment]
Hmm, I think I am completely wrong with how dired works from lisp, I
will need to work more on this to make it working if possible.
Perhaps a full implementation for editing absolute file names will be
neccessary if dired sucks with unrelated files.

Wiil see tomorrow.

-- 
Thierry
Gpg Key fingerprint = 6CEC 7081 AB33 E251 4AB8  5FC2 28D1 7F53 59F2 9997

**Comment by Ambrevar** [comment]
Please see my edited comment on GitHub, I think the one you see from your mailbox is only the first edit.

`C-x C-q` in `wdired` is bound to `wdired-exit` and it will ask whether to apply changes or discard them. Applying changes then is equivalent to `C-c C-c`.

The dired buffer in which the files are put is named `*Find*` at some point.

I referenced `find-name-dired` (or `find-dired`) as a benchmark for this new helm feature since it basically does the same thing, that is, put a selection of files into a dired buffer, ready for editing with wdired.

As I mentioned, when I select a bunch of files with `find-name-dired`:
- If I rename only a subset of them, then wdired will not ask "overwriting" the files that were not renamed.
- No error is produced.
- With files from different folders, wdired has no issue with processing them at the same time.

If `find-name-dired` can do it, I suppose helm can too.

**Comment by thierryvolpiatto** [comment]
Pierre Neidhardt <notifications@github.com> writes:

> If find-name-dired can do it, I suppose helm can too.

Thanks, that's clear.

So the problem is in the way the dired buffer is created, clearly

    (dired ' (foo f1 f2 f3))

is not creating a dired buffer suitable for wdired (IIRC it was in the
past around emacs-22).

-- 
Thierry
Gpg Key fingerprint = 6CEC 7081 AB33 E251 4AB8  5FC2 28D1 7F53 59F2 9997

**Comment by thierryvolpiatto** [comment]
Dired and Wdired are not handling properly `(dired ('foo f1 f2 f3))` I found 3 bugs in wdired while debugging, and even `find-name-dired` is not working correctly as it returns a dired buffer containing
its own directory as subdir! which is wrong.
The only way I see to properly implement edition of marked files is creating a completely new mode
that do not depend of dired and wdired.
The other way would be to fix wdired and dired in emacs, but this is out of my scope seeing how hard it is to contribute to emacs.
So leave this open as a feature request, I will try to work on a new mode for editing hff marked files when I will find time.
Thanks.

**Comment by thierryvolpiatto** [comment]
I have fixed one bug in wdired by advising one of its functions, please try it.

Thanks.

**Comment by thierryvolpiatto** [comment]
If you are using `dired-async-mode` upgrade your emacs-async package (from Melpa, not Elpa), which fix an issue with `wdired-use-interactive-rename` when non-nil.

**Comment by thierryvolpiatto** [comment]
Note that edition of the directory part of files in the dired buffer is not available until emacs-26 (perhaps emacs-25, didn't check), so you will have an error when trying to do so with e.g emacs-24.5.
The variable controlling this is `wdired-create-parent-directories` if available.

**Comment by Ambrevar** [comment]
Thanks for the fixes:
- the `Reading directory` error is gone;
- the broken `*Find*` buffer is gone;
- the second run of wdired repopulates the buffer properly.
- works in `helm-find` too!

Now the only thing that behaves differently compared to a `wdired` run afer a `find-dired` is the confirmation it asks for every file whose name has not changed. Is it possible to change that or is it an Emacs bug?

**Comment by thierryvolpiatto** [comment]
Pierre Neidhardt <notifications@github.com> writes:

> Thanks for the fixes:
>
>   * the Reading directory error is gone;

This was a bug in wdired itself not handling dired-directory as a cons
cell.

>   * the broken *Find* buffer is gone;
>   * the second run of wdired repopulates the buffer properly.
>   * works in helm-find too!

The bug fixed in first place seems to fix also indirectly these last
issues.

> Now the only thing that behaves differently compared to a wdired run
> afer a find-dired is the confirmation it asks for every file whose
> name has not changed. Is it possible to change that or is it an Emacs
> bug?

I have disabled the confirmations for dired-async (see last commit in
emacs-async), don't know if you are using it, I didn't try yet with
dred-async-mode disabled, if there is no confirmations it is an emacs
bug.
Be sure to keep wdired-use-interactive-rename set to non-nil, even if it
will have no effect (for now) with dired-async enabled.


Thanks for your feedback.


--
Thierry
Gpg Key fingerprint = 6CEC 7081 AB33 E251 4AB8  5FC2 28D1 7F53 59F2 9997

**Comment by Ambrevar** [comment]
Hmm... With lated emacs-async and dired-async-mode I still get prompted for confirmation on renaming, when it is a no-op. Not sure what I'm doing wrong.

**Comment by thierryvolpiatto** [comment]
Pierre Neidhardt <notifications@github.com> writes:

> Hmm... With lated emacs-async and dired-async-mode I still get
> prompted for confirmation on renaming, when it is a no-op.

Not sure to understand what operation would be a no-op here.

> Not sure what I'm doing wrong.

Here I am not prompted at all, can you describe exactly what you did
step by step ?

Thanks.

--
Thierry
Gpg Key fingerprint = 6CEC 7081 AB33 E251 4AB8  5FC2 28D1 7F53 59F2 9997

**Comment by thierryvolpiatto** [comment]
Pierre Neidhardt <notifications@github.com> writes:

> Hmm... With lated emacs-async and dired-async-mode I still get
> prompted for confirmation on renaming, when it is a no-op. Not sure
> what I'm doing wrong.

Oh, I see, it is because you use C-x C-q to exit wdired isn't it ?
If you use C-x C-s you should not be prompted.

>
> —
> You are receiving this because you modified the open/close state.
> Reply to this email directly, view it on GitHub, or mute the thread.*


--
Thierry
Gpg Key fingerprint = 6CEC 7081 AB33 E251 4AB8  5FC2 28D1 7F53 59F2 9997

**Comment by thierryvolpiatto** [comment]
Pierre Neidhardt <notifications@github.com> writes:

> Hmm... With lated emacs-async and dired-async-mode I still get
> prompted for confirmation on renaming, when it is a no-op. Not sure
> what I'm doing wrong.

Nothing wrong, another emacs bug in `wdired-get-filename` that should be
fixed now by advice.

Thanks.

--
Thierry
Gpg Key fingerprint = 6CEC 7081 AB33 E251 4AB8  5FC2 28D1 7F53 59F2 9997

**Comment by Ambrevar** [comment]
It works.

I get an error though when I turn on wdired with `C-x C-q`:
```
Debugger entered--Lisp error: (wrong-type-argument stringp nil)
  file-name-absolute-p(nil)
  (or no-dir old (file-name-absolute-p file))
  (if (or no-dir old (file-name-absolute-p file)) file (and file (> (length file) 0) (expand-file-name file (dired-current-directory))))
  (save-excursion (setq end (line-end-position)) (beginning-of-line) (setq beg (next-single-property-change (point) (quote old-name) nil end)) (if (eq beg end) nil (if old (setq file (get-text-property beg (quote old-name))) (setq end (next-single-property-change beg (quote end-name))) (setq file (buffer-substring-no-properties (1+ beg) end))) (and file (setq file (condition-case _err (apply (function wdired-normalize-filename) (list file (not old))) (wrong-number-of-arguments (wdired-normalize-filename file)))))) (if (or no-dir old (file-name-absolute-p file)) file (and file (> (length file) 0) (expand-file-name file (dired-current-directory)))))
  (let (beg end file) (save-excursion (setq end (line-end-position)) (beginning-of-line) (setq beg (next-single-property-change (point) (quote old-name) nil end)) (if (eq beg end) nil (if old (setq file (get-text-property beg (quote old-name))) (setq end (next-single-property-change beg (quote end-name))) (setq file (buffer-substring-no-properties (1+ beg) end))) (and file (setq file (condition-case _err (apply (function wdired-normalize-filename) (list file ...)) (wrong-number-of-arguments (wdired-normalize-filename file)))))) (if (or no-dir old (file-name-absolute-p file)) file (and file (> (length file) 0) (expand-file-name file (dired-current-directory))))))
  helm--advice-wdired-get-filename()
  apply(helm--advice-wdired-get-filename nil)
  wdired-get-filename()
  wdired-preprocess-perms()
  wdired-change-to-wdired-mode()
  dired-toggle-read-only()
  funcall-interactively(dired-toggle-read-only)
  call-interactively(dired-toggle-read-only nil nil)
  command-execute(dired-toggle-read-only)
```

**Comment by thierryvolpiatto** [comment]
Pierre Neidhardt <notifications@github.com> writes:

> It works.
>
> I get an error though when I turn on wdired with C-x C-q:
>
> Debugger entered--Lisp error: (wrong-type-argument stringp nil)
>   file-name-absolute-p(nil)

Couldn't reproduce, but I have protected the call to
file-name-absolute-p, so you should not have anymore this error.

Thanks.

-- 
Thierry
Gpg Key fingerprint = 6CEC 7081 AB33 E251 4AB8  5FC2 28D1 7F53 59F2 9997
