### ISSUE TITLE
"Marker points into wrong buffer" with helm-mark-ring and Evil

### ISSUE THREAD

**Issue by Ambrevar** [emacs-helm/helm#1891]
This issues has already been reported on Evil's issue tracker https://github.com/emacs-evil/evil/issues/845 but no progress was made so far.  It is not clear whether the issue comes from Helm, Evil, or an incompatibility between both.  Maybe you can help.

## Expected behavior

With follow-mode on, navigate through the different marks.

## Actual behavior (from `emacs-helm.sh` if possible, see note at the bottom)

Some entries follow up to seemingly random locations and an error message is displayed:
```
Marker points into wrong buffer
```

## Steps to reproduce (recipe)

- Install latest Evil.
- Start Emacs, require helm and evil. **Update:** No need to turn on evil mode.
- <s>Use some vim/Evil movements (e.g. `{` and `}` over a sequence of paragraphs) to populate the mark ring.</s> **Update:** Make two different marks with `C-SPC`.
- Call `helm-mark-ring` and make sure you have at least 2 entries.
- Enable `helm-follow-mode` with `C-c C-f`.
- Move around the Helm entries up and down until you get the error.

## Backtraces if any (`M-x toggle-debug-on-error`)

```
Debugger entered--Lisp error: (error "Marker points into wrong buffer" #<marker in no buffer>)
  helm-goto-char(#<marker in no buffer>)
  helm-mark-ring-default-action(#<marker in no buffer>)
  helm-execute-selection-action-1(#<marker in no buffer> (("Goto line" . helm-mark-ring-default-action)) t)
  helm-execute-persistent-action()
  #[0 "�\205��\301 \207" [helm-alive-p helm-execute-persistent-action] 1]()
  apply(#[0 "�\205��\301 \207" [helm-alive-p helm-execute-persistent-action] 1] nil)
  timer-event-handler([t 0 0 10000 nil #[0 "�\205��\301 \207" [helm-alive-p helm-execute-persistent-action] 1] nil idle 0])
  read-from-minibuffer("pattern: " <TRUNCATED>
  helm-read-pattern-maybe(nil nil nil noresume nil nil nil)
  helm-internal((helm-source-mark-ring helm-source-global-mark-ring) nil nil noresume nil "*helm mark ring*" nil nil nil)
  apply(helm-internal ((helm-source-mark-ring helm-source-global-mark-ring) nil nil noresume nil "*helm mark ring*" nil nil nil))
  helm((helm-source-mark-ring helm-source-global-mark-ring) nil nil noresume nil "*helm mark ring*" nil nil nil)
  apply(helm ((helm-source-mark-ring helm-source-global-mark-ring) nil nil noresume nil "*helm mark ring*" nil nil nil))
  helm(:sources (helm-source-mark-ring helm-source-global-mark-ring) :resume noresume :buffer "*helm mark ring*")
  helm-all-mark-rings()
  (if rectangle-mark-mode (rectangle-exchange-point-and-mark) (helm-all-mark-rings))
  helm-mark-or-exchange-rect()
  funcall-interactively(helm-mark-or-exchange-rect)
  call-interactively(helm-mark-or-exchange-rect nil nil)
  command-execute(helm-mark-or-exchange-rect)
```

Content of the mark-ring:
```
(#<marker at 190 in bar.c> #<marker at 143 in bar.c> #<marker at 190 in bar.c> #<marker at 143 in bar.c> #<marker at 190 in bar.c> #<marker at 23 in bar.c> #<marker at 190 in bar.c> #<marker at 143 in bar.c> #<marker at 190 in bar.c> #<marker at 143 in bar.c> #<marker at 190 in bar.c> #<marker at 23 in bar.c> #<marker at 190 in bar.c> #<marker at 143 in bar.c> #<marker at 245 in bar.c> #<marker at 245 in bar.c>)
```

## Describe versions of Helm, Emacs, operating system, etc.

Helm: MELPA
Evil: MELPA
OS: Arch Linux, Gentoo, Ubuntu...

## Are you using `emacs-helm.sh` to reproduce this bug (yes/no):

With Evil activated.

**Comment by thierryvolpiatto** [comment]
Pierre Neidhardt <notifications@github.com> writes:

> This issues has already been reported on Evil's issue tracker
> emacs-evil/evil#845 but no progress was made so far. It is not clear
> whether the issue comes from Helm, Evil, or an incompatibility between
> both. Maybe you can help.
>
> Expected behavior
>
> With follow-mode on, navigate through the different marks.
>
> Actual behavior (from emacs-helm.sh if possible, see note at the bottom)
>   (if rectangle-mark-mode (rectangle-exchange-point-and-mark) (helm-all-mark-rings))
>   helm-mark-or-exchange-rect()
>   funcall-interactively(helm-mark-or-exchange-rect)

What is `helm-mark-or-exchange-rect`?

--
Thierry

**Comment by Ambrevar** [comment]
Sorry, that was the trace from a non-vanilla session.  Here is the vanilla trace:
```
* Helm error
(error "Marker points into wrong buffer" #<marker in no buffer>)
  helm-goto-char(#<marker in no buffer>)
  helm-mark-ring-default-action(#<marker in no buffer>)
  helm-execute-selection-action-1(#<marker in no buffer> (("Goto line" . helm-mark-ring-default-action)) t)
  helm-execute-persistent-action()
  #[0 "\205^@\301 \207" [helm-alive-p helm-execute-persistent-action] 1]()
  apply(#[0 "\205^@\301 \207" [helm-alive-p helm-execute-persistent-action] 1] nil)
  timer-event-handler([t 0 0 10000 nil #[0 "\205^@\301 \207" [helm-alive-p helm-execute-persistent-action] 1] nil idle 0])
  read-from-minibuffer("pattern: " nil (keymap (f13 lambda nil (interactive) (helm-select-nth-action 12)) (f12 lambda nil (interactive) (helm-select-nth-action 11)) (f11 lambda nil (interactive) (helm-select-nth-action 10)) (f10 lambda nil (interactive) (helm-select-nth-action 9)) (f9 lambda nil (interactive) (helm-select-nth-action 8)) (f8 lambda nil (interactive) (helm-select-nth-action 7)) (f7 lambda nil (interactive) (helm-select-nth-action 6)) (f6 lambda nil (interactive) (helm-select-nth-action 5)) (f5 lambda nil (interactive) (helm-select-nth-action 4)) (f4 lambda nil (interactive) (helm-select-nth-action 3)) (f3 lambda nil (interactive) (helm-select-nth-action 2)) (f2 lambda nil (interactive) (helm-select-nth-action 1)) (menu-bar keymap (help-menu keymap (describe keymap (describe-mode . helm-help)))) (help keymap (109 . helm-help)) (23 . #[0 "\306\307\310\311\312\305!\313\"\314$\216\315\302!\210\316\304!\317\211\211\301=\203'
```

I realized something else: I don't need to turn Evil on to generate the issue, and I don't even need any other mark than a few marks created with `C-SPC`.

My `init.el`:
```
(require 'helm-config)
(require 'evil
```

**Comment by thierryvolpiatto** [comment]
Pierre Neidhardt <notifications@github.com> writes:

> I realized something else: I don't need to turn Evil on to generate
> the issue

But evil is loaded, right?
Can you reproduce without evil loaded?

Here without evil (I don't use this) I can't reproduce, seems evil is
doing something wrong with marks to end up with #<marker in no buffer>?


-- 
Thierry

**Comment by Ambrevar** [comment]
Evil is loaded with `require`, but it's the evil mode is not on, i.e. the keybindings remain Emacs bndings.
I cannot reproduce without Evil either (which is why I opened the issue on Evil's bugtracker first).
The possibilities are narrowed down: it must come from some incompatibility between Helm and the code Evil runs/loads when it's `require`d.

**Comment by Ambrevar** [comment]
I also noticed that the mark-ring gets corrupted: some elements get replaced by other elements of the ring, so that in the end there are a lot of duplicates.  Example:

```
(#<marker at 3736 in todo.org> #<marker at 3736 in todo.org> #<marker at 3736 in todo.org> #<marker at 3736 in todo.org> #<marker at 3736 in todo.org> #<marker at 3736 in todo.org> #<marker at 3736 in todo.org> #<marker at 3736 in todo.org> #<marker at 3736 in todo.org> #<marker at 3736 in todo.org> #<marker at 3696 in todo.org> #<marker at 338 in todo.org> #<marker at 3696 in todo.org> #<marker at 338 in todo.org> #<marker at 3696 in todo.org> #<marker at 3736 in todo.org>)
```

**Comment by thierryvolpiatto** [comment]
Pierre Neidhardt <notifications@github.com> writes:

> I also noticed that the mark-ring gets corrupted: some elements get
> replaced by other elements of the ring, so that in the end there are a
> lot of duplicates.

Not here without using evil:

(#<marker at 11803 in helm-ring.el> #<marker at 11240 in helm-ring.el> #<marker at 10979 in helm-ring.el> #<marker at 10717 in helm-ring.el> #<marker at 10337 in helm-ring.el> #<marker at 9324 in helm-ring.el> #<marker at 9678 in helm-ring.el> #<marker at 4472 in helm-ring.el>)

--
Thierry

**Comment by Ambrevar** [comment]
Of course, all issues in this report imply that Evil is `require`d.

**Comment by thierryvolpiatto** [comment]
Pierre Neidhardt <notifications@github.com> writes:

> Of course, all issues in this report imply that Evil is required.

Yes, but if helm without evil have no duplicates, what about evil (just
loaded, not activated) without helm loaded ?

-- 
Thierry

**Comment by Ambrevar** [comment]
Some updates: https://github.com/emacs-evil/evil/issues/845
Bug was reproduced.

`helm-mark-ring` is a sync source, so I'm not quite sure why a timer would be involved.  Any clue on this?

I've investigated the state of the mark ring a little bit:

- Without helm/evil, well, it only changes on C-SPC and the like.  Mostly explicit commands.

- With Helm only, starting `helm-mark-ring`, browsing with follow mode on, and then quitting with `C-g` does not modify the mark-ring.  If however I confirm instead of quitting (`RET`), then a _new mark_ is added to the ring.  (The previous entries are left untouched.)  I'm not sure why that is, considering it's a _ring_, it should only change it's starting position, shouldn't it?  I think there is something wrong here.

- With Evil only, I get a similar behaviour when I set some marks and I navigate them with `C-o`/`C-i`.

- With Helm+Evil, it corrupts the entire ring: markers are duplicated, replaced, swapped, etc.  There might be a pattern but I haven't figured it out yet.

**Comment by thierryvolpiatto** [comment]
Pierre Neidhardt <notifications@github.com> writes:

> Some updates: emacs-evil/evil#845
> Bug was reproduced.
>
> helm-mark-ring is a sync source, so I'm not quite sure why a timer
> would be involved. Any clue on this?

Helm is always using a timer, in any kind of sources.

>
> I've investigated the state of the mark ring a little bit:
>
>   * Without helm/evil, well, it only changes on C-SPC and the like. Mostly explicit commands.
>    
>   * With Helm only, starting helm-mark-ring, browsing with follow mode on, and then quitting with C-g does not modify the mark-ring. If however I confirm
>     instead of quitting (RET), then a new mark is added to the ring. (The previous entries are left untouched.) I'm not sure why that is, considering it's a
>     ring, it should only change it's starting position, shouldn't it? I think there is something wrong here.
>    
>   * With Evil only, I get a similar behaviour when I set some marks and I navigate them with C-o/C-i.
>    
>   * With Helm+Evil, it corrupts the entire ring: markers are duplicated, replaced, swapped, etc. There might be a pattern but I haven't figured it out yet.

Can you reproduce by reverting b518c23 (see issue #1770). 

Thanks.

-- 
Thierry

**Comment by Ambrevar** [comment]
I checked out 178a216, I can still reproduce.
Can you reproduce yourself?

**Comment by thierryvolpiatto** [comment]
Pierre Neidhardt <notifications@github.com> writes:

> I checked out 178a216, I can still reproduce.
> Can you reproduce yourself?

I am not using evil.

-- 
Thierry

**Comment by Ambrevar** [comment]
I understand, but can you install it? It's on MELPA, there is nothing to configure but ``require 'evil)`.

**Comment by thierryvolpiatto** [comment]
Pierre Neidhardt <notifications@github.com> writes:

> I understand, but can you install it? It's on MELPA, there is nothing to configure but ``require 'evil)`.

I could reproduce duplicates with only helm, should be fixed now, I have
no more duplicates.

Then, I have installed evil and required it, and yes I have now duplicates,
but I have no errors from helm, I can navigate tags with follow-mode
enabled and jump to a tag with RET as expected.

> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub, or mute the thread.*


-- 
Thierry

**Comment by thierryvolpiatto** [comment]
After investigating I think the problem doesn't come from evil nor helm but from `push-mark` which doesn't care of dups, advicing it fixes the problem, see:
https://github.com/thierryvolpiatto/emacs-tv-config/blob/master/.emacs.el#L227

**Comment by Ambrevar** [comment]
- With latest commit I still have the issue.
- Advising `push-mark` seems to fix it for good.

I need to do more thorough testing.

Thank you so much for this, this issue was by far one of the biggest blockers.

**Comment by Ambrevar** [comment]
I've had a look at your patch: looks good to me, but I wonder if upstream like `cl-loop`s...
The cl-lib is require in `simple.el` where `push-mark` is defined, but only for `cl-assert`.

Regardless, would you submit your patch upstream?
I can do it too.

**Comment by Ambrevar** [comment]
That being said, why do mark duplicates cause `helm-mark-ring` to raise errors?

**Comment by thierryvolpiatto** [comment]
Pierre Neidhardt <notifications@github.com> writes:

> I've had a look at your patch: looks good to me, but I wonder if
> upstream like cl-loops...

They don't.

> The cl-lib is require in simple.el where push-mark is defined, but only for cl-assert.

Sadly yes.

> Regardless, would you submit your patch upstream?

No, I don't submit bugs nor patchs to emacs anymore.

> I can do it too.

If you want, rewrite the patch without cl-loop and submit as yourself,
no problems.

But the fix if accepted will be available only for last emacs.

-- 
Thierry

**Comment by Ambrevar** [comment]
Before submitting, I'd need to provide an explanation as for _why_ this fixes the issue (my last comment).  Can you explain?

**Comment by thierryvolpiatto** [comment]
Pierre Neidhardt <notifications@github.com> writes:

> Before submitting, I'd need to provide an explanation as for why this
> fixes the issue (my last comment). Can you explain?

This advice fix two things, the first our issue and the
second update the global mark ring to most recent mark, it also remove
old entries for same buffer.
Perhaps you should report only the first issue and make a second report
for global ring.

So for our issue, the original code push the old mark to mark-ring,
which cause dups when this same marker is already in mark-ring whereas
the new code ensure to remove the marker before adding it on top:

    ;;old:
    (setq mark-ring (cons (copy-marker (mark-marker)) mark-ring))
    ;;new:
    (setq mark-ring (cons marker (delete marker mark-ring)))


--
Thierry

**Comment by Ambrevar** [comment]
I understand, but why did the duplicates raise the `"Marker points into wrong buffer"` error in `helm-mark-ring`?

**Comment by thierryvolpiatto** [comment]
Pierre Neidhardt <notifications@github.com> writes:

> I understand, but why did the duplicates raise the "Marker points into wrong buffer" error in helm-mark-ring?

Don't know, I never had this error (even with evil loaded), I only noticed duplicates.

Apparently with no duplicates you don't have such errors anymore?

-- 
Thierry

**Comment by Ambrevar** [comment]
Apparently.  So you could not reproduce?  I'm not sure that will give much incentive to get any patch accepted upstream, but I'll try anyways.

**Comment by thierryvolpiatto** [comment]
Pierre Neidhardt <notifications@github.com> writes:

> Apparently. So you could not reproduce? I'm not sure that will give
> much incentive to get any patch accepted upstream, but I'll try
> anyways.

To reproduce you have from emacs -Q to use C-SPC C-SPC, then move point
somewhere and eval:

(set-marker (mark-marker) (point))
(push-mark)
mark-ring

You should have now one duplicate.

>
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub, or mute the thread.*


-- 
Thierry

**Comment by thierryvolpiatto** [comment]
I think they never take care of this because AFAIK there is no ways to use mark-ring in emacs, only the head of the ring, so duplicates are not a problem.

**Comment by Ambrevar** [comment]
That's a good point.

**Comment by Ambrevar** [comment]
Let's keep in mind though that there still _is_ a bug in Helm's code: it should not fail when the mark-ring has duplicates.

**Comment by thierryvolpiatto** [comment]
Pierre Neidhardt <notifications@github.com> writes:

> Let's keep in mind though that there still is a bug in Helm's code: it should not fail when the mark-ring has duplicates.

It doesn't, at least here.

-- 
Thierry

**Comment by thierryvolpiatto** [comment]
What about providing the advice in helm?
It was provided before but only fixing the global ring, and was provided as a mode, I removed it because it was unrelated to helm (helm mark-ring was working with and without advice), but now that you say it is causing a real bug when evil is enabled, we could provide the advice unconditionally.
Anyway if upstream accepts the change, it will be only in months, will not be in next emacs release and will not cover other versions of emacs (olders).
WDYT?

**Comment by Ambrevar** [comment]
Sorry to insist, but I'm not sure I understood from your comments:

Can you reproduce the issue with my recipe (both helm and evil required) without the advice?

@wasamasa could reproduce, so if you can't that would be puzzling.

As for the advice: Yes, it could be a good thing, but let's do it cleanly and make sure turning Helm off removes the advice.  It would also be a good test ground as there are hundreds users of Helm-unstable, so we would know probably quite soon if this breaks anything.  So I suggest you don't publish a stable release for a little while (say 1 month) so we don't force-break everything.

**Comment by thierryvolpiatto** [comment]
Pierre Neidhardt <notifications@github.com> writes:

> Sorry to insist, but I'm not sure I understood from your comments:
>
> Can you reproduce the issue with my recipe (both helm and evil
> required) without the advice?

I got duplicates but didn't have error when jumping to mark from helm.
Perhaps I didn't insist enough?
I will try to reinstall evil an try again soon.

>
> @wasamasa could reproduce, so if you can't that would be puzzling.
>
> As for the advice: Yes, it could be a good thing, but let's do it
> cleanly and make sure turning Helm off removes the advice.

You can accumulate duplicates in mark-ring outside of helm with any code
modifying mark and using push-mark.
So removing the advice when helm is turned of will not prevent us to
have dups in mark-ring.
Otherwise it is what I generally do, removing advices after each helm session.

-- 
Thierry

**Comment by thierryvolpiatto** [comment]
Pierre Neidhardt <notifications@github.com> writes:

> Can you reproduce the issue with my recipe (both helm and evil required) without the advice?

Could not reproduce the error after reinstalling evil and retrying.

> @wasamasa could reproduce, so if you can't that would be puzzling.

Indeed.

> As for the advice: Yes, it could be a good thing, but let's do it
> cleanly and make sure turning Helm off removes the advice.

I could get duplicates from emacs -Q just typing C-SPC
C-SPC at different places in a buffer.
So the advice should be always enabled IMO.

-- 
Thierry

**Comment by Ambrevar** [comment]
Bug reported upstream: https://debbugs.gnu.org/cgi/bugreport.cgi?bug=29110

**Comment by Ambrevar** [comment]
And here is a suggestion from Noam Postavsky:

> One thing to note is that
> push-mark resets markers before discarding (so that they no longer point
> to any buffer).  Maybe Helm or Evil keep another reference to a
> discarded marker, and try to use it without checking?  If you have a way
> to reproduce the problem, you can check if bumping up mark-ring-max to a
> very large number has any effect.
>
>     (defun push-mark (&optional location nomsg activate)
>        ...
>         (when (> (length mark-ring) mark-ring-max)
>           (move-marker (car (nthcdr mark-ring-max mark-ring)) nil)
>           (setcdr (nthcdr (1- mark-ring-max) mark-ring) nil)))
>        ...
>         (when (> (length global-mark-ring) global-mark-ring-max)
>           (move-marker (car (nthcdr global-mark-ring-max global-mark-ring)) nil)
>           (setcdr (nthcdr (1- global-mark-ring-max) global-mark-ring) nil)))

The discussion suggests that have duplicates in the mark ring is both fine and intended.
The above suggestion might be a good lead to follow.

**Comment by thierryvolpiatto** [comment]
Pierre Neidhardt <notifications@github.com> writes:

> The discussion suggests that have duplicates in the mark ring is both
> fine and intended.

As expected, no surprise.

> The above suggestion might be a good lead to follow.

Already know this and that's fine as long as there is not a serie of
dereferenced marker in queue, which doesn't happen with a regular use of
markers, but happens if one starts for some reasons to dereference
markers (what Evil does apparently IIUC the comment of its developer).

I pushed a fix that check if marker is referenced to a buffer before
jumping to it and otherwise delete this unreferenced marker from mark-ring.

I made also a defcustom to disable push-mark advice for the fans of
duplicates.

-- 
Thierry

**Comment by Ambrevar** [comment]
When the advice is removed, the issue is still here.

I might be missing something with the new option, but it seems that turning it off via Custom or with
`(setq helm-advice-push-mark nil)` does not remove the advice.

I think the code should be
```
(defcustom helm-advice-push-mark t
  "Override `push-mark' with a version avoiding duplicates when non nil."
  :group 'helm
  :type 'boolean
  :set (lambda (var val)
         (set var val)
         (if (symbol-value var)
             (advice-add 'push-mark :override #'helm--advice-push-mark)
           (advice-remove 'push-mark #'helm--advice-push-mark))))
```

**Comment by thierryvolpiatto** [comment]
Pierre Neidhardt <notifications@github.com> writes:

> When the advice is removed, the issue is still here.

Of course it is, and we can't do anything to fix it, the ball is now in
Evil side.

> I might be missing something with the new option, but it seems that
> turning it off via Custom or with (setq helm-advice-push-mark nil)
> does not remove the advice.

Thanks fixed.


--
Thierry

**Comment by thierryvolpiatto** [comment]
I think this can be closed as there is no much more to do on our side.
