### ISSUE TITLE
Helm adds space after completing directory name in M-x shell

### ISSUE THREAD

**Issue by holtzermann17** [emacs-helm/helm#2274]
## Expected behavior

I would expect to see "`cd ~/Downloads/`" <- **no trailing space** as the result of completion when I press `cd ~/Down<TAB>` in a shell buffer.  This behaviour is useful because it allows to change to subdirectories quickly, by pressing <kbd>TAB</kbd> again.

## Actual behavior (from `emacs-helm.sh` if possible, see note at the bottom)

Instead, I see "`cd ~/Downloads/ `" <- **with a trailing space**.

## Steps to reproduce (recipe)

Reproduction:
```
~/.emacs.d/elpa/helm-20200126.1804$ ./emacs-helm.sh
M-x shell
cd ~/Down<TAB>
```

...Note that the Expected Behaviour above is produced if I instead run  `emacs -Q --no-site-file`. In other words, Helm changes a default behaviour in a way that isn't entirely obvious, since I never see a Helm buffer pop up in this interaction.

## Describe versions of Helm, Emacs, operating system, etc.

GNU Emacs 28.0.50 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.22.30, cairo version 1.15.10) of 2020-01-27

## Are you using `emacs-helm.sh` to reproduce this bug? (yes/no):

Yes

## Are you using Spacemacs? (yes/no):

No

**Comment by thierryvolpiatto** [comment]
Joe Corneli <notifications@github.com> writes:

> Instead, I see "cd ~/Downloads/ " with a trailing space.

Indeed, should be fixed now.
Thanks to catch this.

-- 
Thierry

Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by manuel-uberti** [comment]
@thierryvolpiatto just an FYI. I cloned `helm` repository and from `emacs-helm.sh` the problem is still present.

**Comment by thierryvolpiatto** [comment]
Manuel Uberti <notifications@github.com> writes:

> @thierryvolpiatto just an FYI. I cloned helm repository and from emacs-helm.sh the problem is still present.

Yes the issue is here again after fixing issues #2356 and #2265, should
be fixed in devel branch (will merge soon) hopefully without breaking
anything else.

Thanks.

-- 
Thierry

**Comment by manuel-uberti** [comment]
Fantastic, it works as expected now. Thank you for the quick fix.
