### ISSUE TITLE
Most recent commit breaks use via use-package + straight.el

### ISSUE THREAD

**Issue by mgsloan** [emacs-helm/helm#2481]
### What happened?

```
Error (use-package): helm-projectile/:catch: Cannot open load file: No such file or directory, helm
Error (use-package): helm-rg/:catch: Cannot open load file: No such file or directory, helm
```

My use-package + [straight.el](https://github.com/raxod502/straight.el) config has:

```
(use-package helm-projectile)
(use-package helm-rg)

(use-package helm
   ...
)
```

I just used `straight-fetch-all` to pull head versions of all git repos (it would be nice if there was a way to pull latest stable versions!).  Omitting a7b9e898296142465c0857b2d201d8d828ba7b05 (using v3.8.4) fixes this issue. 

### How to reproduce?

I could try to make a minimal repo if helpful, but maybe what's going wrong here is obvious.  I'm not too knowledgeable about this stuff.  Perhaps a recipe needs to be updated now that helm-core exists?

Sorry, gonna check the "I agree using a minimal configuration" box anyway.  I understand the purpose of this is to eliminate interactions with other scripts, but since the problem goes away by omitting the HEAD commit to helm, it seems extremely unlikely that this involves other scripts (beyond straight.el + use-package)

### Helm Version

Master branch

### Emacs Version

Emacs-27.1

### OS

GNU/Linux

### Relevant backtrace (if possible)

```text
Debugger entered--Lisp error: (file-missing "Cannot open load file" "No such file or directory" "helm")
  require(helm)
  byte-code("\300\301!\210\300\302!\210\300\303!\210\300\304!\210\300\305!\210\300\306!\210\300\307!\210\300\310!\210\300\311!\210\312\313\314\315\316\317\320\302\320\305\321\322&\13..." [require subr-x projectile cl-lib grep helm helm-types helm-locate helm-buffers helm-files custom-declare-group helm-projectile nil "Helm support for projectile." :prefix "helm-projectile-" :group :link (url-link :tag "GitHub" "https://github.com/bbatsov/helm-projectile") custom-declare-variable helm-projectile-truncate-lines funcall function #f(compiled-function () #<bytecode 0x1572974d5561>) "Truncate lines in helm projectile commands when no..." :type boolean helm-projectile-fuzzy-match #f(compiled-function () #<bytecode 0x1572974d5571>) "Enable fuzzy matching for Helm Projectile commands..."] 12)
  require(helm-projectile nil t)
  (not (require 'helm-projectile nil t))
  (if (not (require 'helm-projectile nil t)) (display-warning 'use-package (format "Cannot load %s" 'helm-projectile) :error))
  (condition-case err (if (not (require 'helm-projectile nil t)) (display-warning 'use-package (format "Cannot load %s" 'helm-projectile) :error)) ((debug error) (funcall use-package--warning14 :catch err)))
  eval-buffer(#<buffer  *load*-723247> nil "/home/mgsloan/.emacs.d/global.el" nil t)  ; Reading at buffer position 7050
  load-with-code-conversion("/home/mgsloan/.emacs.d/global.el" "/home/mgsloan/.emacs.d/global.el" nil nil)
  load("/home/mgsloan/.emacs.d/global.el")
  (while (consp --cl-var--) (setq name (car --cl-var--)) (load (concat emacs-config-dir name ".el")) (setq --cl-var-- (cdr --cl-var--)))
  (let* ((--cl-var-- configs) (name nil)) (while (consp --cl-var--) (setq name (car --cl-var--)) (load (concat emacs-config-dir name ".el")) (setq --cl-var-- (cdr --cl-var--))) nil)
  eval-buffer(#<buffer  *load*> nil "/home/mgsloan/.emacs.d/init.el" nil t)  ; Reading at buffer position 1249
  load-with-code-conversion("/home/mgsloan/.emacs.d/init.el" "/home/mgsloan/.emacs.d/init.el" t t)
  load("/home/mgsloan/.emacs.d/init" noerror nomessage)
  startup--load-user-init-file(#f(compiled-function () #<bytecode 0x157296f3c2b5>) #f(compiled-function () #<bytecode 0x157296f3c285>) t)
  command-line()
  normal-top-level()
```

### Minimal configuration

- [X] I agree using a minimal configuration

**Comment by tomonacci** [comment]
I ran into this a few hours ago as well. Adding the following three lines to the init file seemingly lets me work around this issue:

```elisp
(setq straight-recipe-overrides nil)
(straight-override-recipe '(helm :files ("*.el" "emacs-helm.sh" (:exclude "helm-core.el" "helm-lib.el" "helm-source.el" "helm-multi-match.el"))))
(straight-override-recipe '(helm-core :files ("helm-core.el" "helm-lib.el" "helm-source.el" "helm-multi-match.el")))
```

This amounts to replacing the `:files` entries in https://github.com/melpa/melpa/blob/master/recipes/helm and https://github.com/melpa/melpa/blob/master/recipes/helm-core with the provided values. The diffs are (apart from removing references to `*-pkg.el` files):

- helm: un-exclude `helm.el`, exclude `helm-core.el`
- helm-core: add `helm-core.el` and remove `helm.el`

With my minimal understanding of both straight.el and helm, I suspect the mechanism behind the issue and the workaround to be:

1. straight.el operates on the raw Git repo, which, after https://github.com/emacs-helm/helm/commit/a7b9e898296142465c0857b2d201d8d828ba7b05, doesn't contain `helm-pkg.el` or `helm-core-pkg.el`.
2. straight.el can harvest dependencies from `Package-Requires` only if the files containing `Package-Requires` are listed in `:files`. Hence, helm-core was not pulled in as a dependency of helm, and therefore helm.el, which was bundled with helm-core, wasn't included, so `No such file or directory, helm`.
3. The preceding point suggests that helm and helm-core should include `helm.el` and `helm-core.el`, respectively, via `:files`. I did that and removed `helm.el` from helm-core so that it isn't duplicated in helm and helm-core. And vice-versa for `helm-core.el`. This actually removes functionality from helm-core but probably since I don't use helm-core in isolation no problems surfaced for me. A proper fix might be to move whatever portion of `helm.el` that is needed in helm-core to `helm-core.el`.

**Comment by wlthomson** [comment]
I also ran into this issue and the workaround documented by @tomonacci is working for me (Ubuntu 21.10, Emacs 27.1).

**Comment by thierryvolpiatto** [comment]
I am sorry for disagreement that cause. I have submitted a PR to Melpa, once merged this should fix the issue.
Thanks.

**Comment by thierryvolpiatto** [comment]
Will Thomson ***@***.***> writes:

>     I am sorry for disagreement that cause. I have submitted a PR to Melpa, once merged this should fix the issue. Thanks.
>    
> Thanks! Could you provide a link to the PR and/or update this issue when the PR is merged?

https://github.com/melpa/melpa/pull/7896

-- 
Thierry

**Comment by gzmask** [comment]
I saw that PR is merged but helm is still broken. probably need some time for it to hit the right place.

**Comment by quinoa42** [comment]
As a workaround after melpa/melpa#7896 is merged, explicitly `(use-package helm-core :straight t)` fixes it.

**Comment by wlthomson** [comment]
> As a workaround after [melpa/melpa#7896](https://github.com/melpa/melpa/pull/7896) is merged, explicitly `(use-package helm-core :straight t)` fixes the error.

Thanks! Note that this only worked for me if `helm-core` is required before `helm`.

**Comment by thierryvolpiatto** [comment]
Will Thomson ***@***.***> writes:

>     As a workaround after melpa/melpa#7896 is merged, explicitly (use-package helm-core :straight t) fixes the error.
>    
> Thanks! Note that this only worked for me if helm-core is required before helm.

Great. Yes actually we have helm-core.el which is an empty file and
helm.el which is the core file containing the most important code, a
better fix would be to have an empty helm.el file (perhaps requiring
helm-core.el) and a helm-core.el file with the contents of the actual
helm.el file.

> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> Triage notifications on the go with GitHub Mobile for iOS or Android.
> You are receiving this because you commented.*Message ID: ***@***.***>


-- 
Thierry

**Comment by thierryvolpiatto** [comment]
> Thanks! Note that this only worked for me if helm-core is required before helm.

This should not be anymore needed because now helm.el is part of helm package and helm-core.el contains the code previously handled by helm.el. Melpa recipes have been updated accordingly.
Closing this now, let me know if you still have problems.
Thanks.
