### ISSUE TITLE
when annotation is used with completing-read, negating first pattern yields a "ghost" candidate at top

### ISSUE THREAD

**Issue by dankessler** [emacs-helm/helm#2651]
### What happened?

This is a follow-up to #2650. I noticed the issue in `org-roam`, where if I was searching for a node and tried to negate the pattern, I would get an empty candidate at the top. Previously, I would also lose my last candidate, but that has been fixed in #2650. 

I was able to isolate this to how `helm` interact with `annotation-function` when it is used as a replacement for `completing-read`.

Side note: when I tried to reproduce this in a clean emacs, the bug from #2650 also resurfaced, but I suspect that that fix has simply not made its way into NonGNU-ELPA.

### How to reproduce?

First, define some simple annotation functions

```
(defun good-annotator (string)
  nil)

(defun bad-annotator-silent (string)
  "")

(defun bad-annotator-loud (string)
  "hello")
```

Next, enable `helm-mode`
```
(helm-mode 1)
```

Now, run the following example

```
(let ((completion-extra-properties '(:annotation-function bad-annotator-loud)))
  (completing-read "Prompt: " '("foo" "bar" "baz")))
```

The candidate list is initially
```
foohello
barhello
bazhello
```
but if we try to negate that with `!xy`, a new entry appears at the top and it becomes
```
hello
foohello
barhello
bazhello
```

We can repeat the experiment, but replacing the annotation-function with `bad-annotator-silent` 
```
(let ((completion-extra-properties '(:annotation-function bad-annotator-silent)))
  (completing-read "Prompt: " '("foo" "bar" "baz")))
```
The initial list looks good, but negating with `!xy` gives a *blank* candidate at the top (presumably the empty string from annotation)
```

foohello
barhello
bazhello
```

If we instead use the `good-annotator` (which returns nil rather than an empty string), then negation works appropriately.

I further experimented with this by calling `helm-comp-read` rather than `completing-read`, and it handles negation correctly. However, calling `helm--completing-read-default` (which I know we're not generally supposed to do), causes the bad behavior again.

For convenience, here's all the code I used for testing

```
(defun good-annotator (string)
  nil)

(defun bad-annotator-silent (string)
  "")

(defun bad-annotator-loud (string)
  "hello")

(helm-mode)

;; With completing-read but helm-intercepts
(let ((completion-extra-properties '(:annotation-function good-annotator)))
  (completing-read "Prompt: " '("foo" "bar" "baz")))

(let ((completion-extra-properties '(:annotation-function bad-annotator-silent)))
  (completing-read "Prompt: " '("foo" "bar" "baz")))

(let ((completion-extra-properties '(:annotation-function bad-annotator-loud)))
  (completing-read "Prompt: " '("foo" "bar" "baz")))


;; Directly use helm-comp-read
(let ((completion-extra-properties '(:annotation-function good-annotator)))
  (helm-comp-read "Prompt: " '("foo" "bar" "baz")))

(let ((completion-extra-properties '(:annotation-function bad-annotator-silent)))
  (helm-comp-read "Prompt: " '("foo" "bar" "baz")))

(let ((completion-extra-properties '(:annotation-function bad-annotator-loud)))
  (helm-comp-read "Prompt: " '("foo" "bar" "baz")))

;; Manually specify helm--completing-read-default
(let ((completion-extra-properties '(:annotation-function good-annotator)))
  (helm--completing-read-default "Prompt: " '("foo" "bar" "baz")))

(let ((completion-extra-properties '(:annotation-function bad-annotator-silent)))
  (helm--completing-read-default "Prompt: " '("foo" "bar" "baz")))

(let ((completion-extra-properties '(:annotation-function bad-annotator-loud)))
  (helm--completing-read-default "Prompt: " '("foo" "bar" "baz")))
```

### Helm Version

Melpa or NonGnuElpa

### Emacs Version

Emacs-29.1

### OS

MacOSX

### Minimal configuration

- [X] I agree using a minimal configuration

**Comment by dankessler** [comment]
Thanks so much! 

It's not a *huge* bother now that #2650 is fixed since I can just avoid choosing the ghost candidate, but I do appreciate you doing such a fantastic job with helm!

**Comment by thierryvolpiatto** [comment]
Dan Kessler ***@***.***> writes:

> What happened?
>
> This is a follow-up to #2650. I noticed the issue in org-roam, where
> if I was searching for a node and tried to negate the pattern, I would
> get an empty candidate at the top.

Should be fixed now by f93f44c0, thanks for the recipes, let me know if
it is now working for you.

> Side note: when I tried to reproduce this in a clean emacs, the bug
> from #2650 also resurfaced, but I suspect that that fix has simply not
> made its way into NonGNU-ELPA.

Probably, let me know if it reappears.


Thanks.

-- 
Thierry

**Comment by thierryvolpiatto** [comment]
Dan Kessler ***@***.***> writes:

> Thanks so much!
>
> It's not a huge bother now that #2650 is fixed since I can just avoid
> choosing the ghost candidate, but I do appreciate you doing such a
> fantastic job with helm!

Thanks!


-- 
Thierry

**Comment by dankessler** [comment]
> Should be fixed now by f93f44c0, thanks for the recipes, let me know if it is now working for you.

Has this not been pushed yet? The most recent commit I see is 4afb13e but it's about 20 hours old and the bug still seems present in that version.

**Comment by thierryvolpiatto** [comment]
Dan Kessler ***@***.***> writes:

> 1.  ( ) text/plain          (*) text/html           
>
>     Should be fixed now by f93f44c0, thanks for the recipes, let me know if it is now working for you.
>    
> Has this not been pushed yet? The most recent commit I see is 4afb13e
> but it's about 20 hours old and the bug still seems present in that
> version.

Oops! Forget to push, now done.

> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you commented.*Message ID: ***@***.***>

-- 
Thierry

**Comment by dankessler** [comment]
I confirm that I no longer get a "ghost" candidate with any of the examples I included here, nor when using `org-roam-node-find` which was where I noticed the bug in the first place.

Thanks so much!
