### ISSUE TITLE
Any windows users here that use Everything Service for Helm Locale? 

### ISSUE THREAD

**Issue by ReneFroger** [emacs-helm/helm#878]
As Windows user, I use Everything for helm locale. :+1:.
When Helm Locate kicks in in Helm-for-files,  the Helm is constantly freezing lately and I'm not able to do anythinginside Emacs.

When I kill es.exe (The Everything Service) in Windows task manager, Emacs and helm are suddenly responding again. 

I noticed this happens often when I'm typing too fast. If I type really so slow, this issue will not arise. :kissing: 
So I guess it has probably something to do with the input lag, which causes Helm to crash? Or it could be propably waiting on any input from es.exe, which will never come, and thus blocking. 

 I wondered why I haven't this issue in the beginning. Starting with clear Emacs config didn't help. So I'm not sure the Everything service or the communication process between Helm and Everything is the culprit. Everything itself responds well on fast input. 

So I'm wondering if there are any Windows users that uses Everything? If so, what could I do in order to debug this issue? 

Thanks in advance. :smiley:.

**Comment by michael-heerdegen** [comment]
AFAICT this can also happen on Linux with locate.

In my case, I think I could defuse the problem a bit by reducing the candidate-number-limit of the locate source:

```
(setq helm-source-locate
      (helm-make-source "Locate" 'helm-locate-source
        :pattern-transformer 'helm-locate-pattern-transformer
        :candidate-number-limit 200))
```

Apart from that, it would be good to fix this, yes.  I'll try to have a look tomorrow.

**Comment by michael-heerdegen** [comment]
Here I see at least two problems:

- When you hit C-g, there is a very large chance that you do that when the process-filter from the locate process is running, and that is helm-output-filter.  Since we don't handle quit events there, Emacs complains about the quit, but apart from that, there is no effect, the quit does neither interrupt or kill the process, nor is the quit propagated to the command loop.  I think the solution is to kill the process when a quit occurs in the process filter.

- When I'm doing M-x helm-locate, enter some small pattern with many matches, and hit <down> to go to line 100 or so, helm still freezes and is unquittable.  That is a different problem.  I tried profiling to find out what helm is doing all the time, and found that `helm-mp-highlight-region' was running all the time.  When I alias it to #'ignore, the problem is fixed.

We must find out why this problem only occurs when the number of the selected candidate is not small, and how we can improve that.

With all these things done, the thing still reacts a bit slowly, because processing all the locate output causes Emacs to use 100% CPU.

I think we should really use a smaller value for the candidate-number-limit of the locate class.  That would make all the problems less serious.

**Comment by thierryvolpiatto** [comment]
Michael Heerdegen <notifications@github.com> writes:

> Here I see at least two problems:

Thanks Michael, I see the same problems on my side, + some others, I am
working on this actually.

-- 
Thierry
Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by michael-heerdegen** [comment]
Much better now, though I still get freezing sometimes with helm-for-files when I select a candidate in a source "somewhere in the middle".

**Comment by thierryvolpiatto** [comment]
Michael Heerdegen <notifications@github.com> writes:

> Much better now,

Good.

> though I still get freezing sometimes with helm-for-files when I
> select a candidate in a source "somewhere in the middle".

Mostly, what I have fixed is C-g'ing, while I was at it I have removed
mp highlighting in all async sources (actual and future), but apparently
it is not enough, but well as I always said, it is an error to have an
async source among other sources (even if it works more or less).

-- 
Thierry
Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by michael-heerdegen** [comment]
Thierry Volpiatto <notifications@github.com> writes:

> but well as I always said, it is an error to have an async source
> among other sources

Because it doesn't work, or per se?

BSF, given that, I think it would be good if I could invoke helm-locate
from helm-for-files without losing the minibuffer content.  It's because
of such little distractions that people want everything in one helm
command I think.

**Comment by thierryvolpiatto** [comment]
Michael Heerdegen <notifications@github.com> writes:

> Thierry Volpiatto <notifications@github.com> writes:
>
>> but well as I always said, it is an error to have an async source
>> among other sources
>
> Because it doesn't work, or per se?
>
> BSF, given that, I think it would be good if I could invoke helm-locate
> from helm-for-files without losing the minibuffer content. It's because
> of such little distractions that people want everything in one helm
> command I think.

You can with something like this:

(defun helm-for-files-switch-to-locate ()
  (interactive)
  (with-helm-buffer
    (helm-set-sources '(helm-source-locate))
    (helm-set-source-filter '("Locate"))))
(define-key helm-map (kbd "<f9>") 'helm-for-files-switch-to-locate)

-- 
Thierry
Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by michael-heerdegen** [comment]
Thierry Volpiatto <notifications@github.com> writes:

> You can with something like this:
>
> (defun helm-for-files-switch-to-locate ()
> (interactive)
> (with-helm-buffer
> (helm-set-sources '(helm-source-locate))
> (helm-set-source-filter '("Locate"))))
> (define-key helm-map (kbd "<f9>") 'helm-for-files-switch-to-locate)

Thanks - but I now see that there were misunderstandings.  From you
saying having an asynchronous source in a multi source helm session
would be an error I concluded that helm-source-locate is not in
helm-for-files-preferred-list's default value.  But I now see it is...my
question was more about how to effectively change to helm-locate from a
helm-for-files that uses no locate source.  But when it's there and
remains there, my question is not relevant.

**Comment by michael-heerdegen** [comment]
FWIW, I'm satisfied with what we have now.

**Comment by thierryvolpiatto** [comment]
See new command `helm-multi-files`.

**Comment by michael-heerdegen** [comment]
Thanks, nice idea!

**Comment by ReneFroger** [comment]
Sorry for my belated response, due to my leave. Perhaps I don't understand it fully how this issue is solved. When I try the new command `helm-multi-files`, I don't get the source `locate` into the Helm buffer. 

When I try: 

```
(setq helm-multi-files-preferred-list
      '(
        helm-source-buffers-list
        helm-source-recentf
        helm-source-files-in-current-dir
        helm-source-locate
        ))  
```

But this don't changes anything at all. When I try `helm-for-files`, with Locate. It's still sometimes freezing, especially when you backspace the input often and lot.

**Comment by thierryvolpiatto** [comment]
ReneFroger <notifications@github.com> writes:

> Sorry for my belated response, due to my leave. Perhaps I don't
> understand it fully how this issue is solved.

The issue was about being able to quit locate properly, it is now fixed.

> When I try the new command helm-multi-files, I don't get the source
> locate into the Helm buffer.

It is the purpose of this command, locate is removed, so you start
typing something in pattern, if you found what you are searching, all
good, otherwise kick in locate by hitting C-c p, switch back to
everything but locate with same command.

> When I try:
>
> (setq helm-multi-files-preferred-list

You have invented this variable :-),

> But this don't changes anything at all.

so it have no effect :-)

-- 
Thierry
Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by ReneFroger** [comment]
>The issue was about being able to quit locate properly, it is now fixed.

Thanks for that. It's related to my issue, I guess? 

> It is the purpose of this command, locate is removed, so you start typing something in pattern, if you found what you are searching, all good, otherwise kick in locate by hitting C-c p, switch back to
everything but locate with same command.

That's another way to do it, indeed. But even with the alternative way to `C-c p`, when I'm typing and deleting the input too fast, Helm Locate still manage to freeze sometimes. So it seems this issue is not solved yet?

**Comment by ReneFroger** [comment]
Is anyone there? Maybe I'm mistaken, but it seems to me that this issue still exists?

**Comment by michael-heerdegen** [comment]
Yes!  It's just that this is a very difficult work to do, and no one has spent time yet.

**Comment by michael-heerdegen** [comment]
But mmh, i hardly tried to reproduce the freezing here, with no success.

What exactly do you do (recipe)?

**Comment by thierryvolpiatto** [comment]
ReneFroger <notifications@github.com> writes:

> Is anyone there? Maybe I'm mistaken, but it seems to me that this issue still exists?

Probably, but I can't reproduce, I will try again on Windows with es.exe
as soon as possible (last time I tried it was working fine though...)

-- 
Thierry
Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by ReneFroger** [comment]
@michael-heerdegen 

I tried to reproduce it, but this issue is unfortunately not consistent and hard to reproduce. :stuck_out_tongue_closed_eyes: 


You could test it, to type random characters until the `Locate source` appears. Then typing it further until Locate gives no relevant results, backspace again until the results in `Locate source` appears. Backspace the characters again, after doing so of twice really fast, it will freeze.

**Comment by thierryvolpiatto** [comment]
ReneFroger <notifications@github.com> writes:

> @michael-heerdegen
>
> I tried to reproduce it, but this issue is unfortunately not
> consistent and hard to reproduce. :st
>
> You could test it, to type random characters until the Locate source
> appears. Then typing it further until Locate gives no relevant
> results, backspace again until the results in Locate source
> appears.

Can't reproduce either.

> Backspace the characters again, after doing so of twice really fast,
> it will freeze.

What do you mean by "freeze", what happen exactly ?
Is emacs blocked ?
Can't you quit with C-g (hit repetitively) ?

-- 
Thierry
Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by thierryvolpiatto** [comment]
Just tried on WindowsXP with emacs-24.4 and using es.exe as backend and
couldn't reproduce.

-- 
Thierry
Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by ReneFroger** [comment]
Could this issue opened again, please?  I got so many times bogged by this issue. It ruins my Helm experience, that I wished that if anyone could tell me what I'm doing wrong, and more important, this issue occurs erratically, so it's not easy for the loved maintainers here to reproduce it.

I made a clip to illustrate my issue:

![helm issue problem](https://cloud.githubusercontent.com/assets/5211845/8264730/3c2b8aa8-16ea-11e5-9020-b6ce11243895.gif)

Typed random words. Emacs freezes sometimes when using Everything source (aka the `find-file-indexer`). The `es.exe` is an instance from `everything.exe` server, running as client. When I kill the client, Helm is responding again.  Sometimes Helm is filling the `locate-source-buffer` inside Helm based on the input, but with tiny amount of results and then Emacs/helm is freezing. 

Maybe I could illustrate this problem more with the clip above. And reminder, could this issue be opened again? Thanks in advance!

**Comment by thierryvolpiatto** [comment]
ReneFroger <notifications@github.com> writes:

> Emacs freezes sometimes when using Everything source (aka the
> find-file-indexer).

Still can't reproduce with Windows7 and emacs-24.5.

> The es.exe is an instance from everything.exe server, running as
> client.

Hmm, I am not aware of this, how did you install es.exe and everything ?

-- 
Thierry
Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by ReneFroger** [comment]
I installed Everything from their Windows binairy installer. Nothing fancy about it. I suspect you will never see es.exe, because this will be active only when Everything is called for input from third-party packages like Helm. 

If you open task manager next to your Emacs window, and run some search in Helm locate source, then es.exe is shortly visible for 1 second, I'm sure.

**Comment by thierryvolpiatto** [comment]
ReneFroger <notifications@github.com> writes:

> I installed Everything from their Windows binairy installer. Nothing
> fancy about it. I suspect you will never see es.exe, because this will
> be active only when Everything is called for input from third-party
> packages like Helm.

Hmm, I have installed Everything but es.exe was not installed, I had to
install it separately and add it to PATH.
It is located at "c:/Program Files/Everything/es.exe"

-- 
Thierry
Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by thierryvolpiatto** [comment]
Also be sure to not have special setting for all about shell.
IOW be sure es.exe is called on a DOS shell and not an Unix one.
If you start with emacs -Q and load a basic helm config, no more, you
will be sure you use the right shell with emacs defaults settings.

-- 
Thierry
Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by ReneFroger** [comment]
When I open DOS and type `es`, then I get a continous searching in files. So you're saying this problem is caused with the wrong shell? Could you elaborate? 

Because Everything is working fine. But sometimes it hangs, especially when I'm typing too fast. So could you explain to me the relation of this with DOS shell, because it worked fine. I don't see the relation with the erradically hang-on sometimes.

**Comment by thierryvolpiatto** [comment]
ReneFroger <notifications@github.com> writes:

> When I open DOS and type es, then I get a continous searching in
> files. So you're saying this problem is caused with the wrong shell?
> Could you elaborate?

The point is that you should not force emacs using a bash shell you have
somewhere (e.g cygwin) when your emacs is not running in such shell.
There is a variable to change this, I can't remember its name.
But I think you didn't do this.

> Because Everything is working fine. But sometimes it hangs, especially
> when I'm typing too fast. So could you explain to me the relation of
> this with DOS shell, because it worked fine. I don't see the relation
> with the erradically hang-on sometimes.

Forget it, the problem is if you force in background the command es.exe
running in something else than a DOS shell.
We had an issue with one user, that was making emacs crashes.

I am affraid I have nothing to do on helm side, it looks more emacs
working badly with async processes in Windows as we have not this
problem in GNU/Linux.

To fix it, the only way to know what is happening is running your emacs
in gdb with preferably an emacs compiled by yourself, but I have no idea
on how to do that on Windows.

Or just switch to GNU/Linux box, it will fix all your problems :-)

-- 
Thierry
Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by ReneFroger** [comment]
For future reference, I tried locate32.cogit.net now, seems more stable regarding the issues of helm, compared with the everything source. So for everyone that faces the same issue, I recommend to try locate32 for Windows.

**Comment by GlebTyazhyolov** [comment]
I met the same issue that ReneFroger explained.
System is Windows 7
emacs-25.0.94.2

emacs freezes after helm-locate string changed few times
es.exe keep showing in process list with zero CPU activity
emacs backs to life if es.exe killed via proccess manager

Will try Rene solution
