### ISSUE TITLE
Symbol's function definition is void: eieio-make-class-predicate

### ISSUE THREAD

**Issue by zijianyue** [emacs-helm/helm#932]
Helm can not start in the latest emacs.

GNU Emacs 25.0.50.1 (i686-pc-mingw32) of 2015-03-15 on LEG570

**Comment by michael-heerdegen** [comment]
Please rebuild your Emacs and re-make helm, there were eieio related problems in the last days, but everything should work now (at least it does for me).  Thanks.

**Comment by LeoUfimtsev** [comment]
Thank you, this fixed my problem also.

**Comment by m-cat** [comment]
I'm getting this same error and I'm not sure what is meant by "re-make helm". I tried deleting helm and reinstalling but the error persists. I don't think rebuilding emacs would help, I'm seeing this error on two machines, both running Emacs 24 (and sharing the same .emacs.d). It works if I run Emacs 26, but I would like to be able to run an older Emacs version sometimes when testing for version compatibility. 

I hope someone sees this and can help, if not I'll write a new issue.

**Comment by xiongtx** [comment]
Upgrade Helm, then **restart** Emacs. Does the error persist?

**Comment by m-cat** [comment]
Sorry, I was able to diagnose my issue with the `--debug-init` flag. The problem was coming from helm-descbinds, which I deleted and reinstalled. Thanks for the help!

**Comment by thierryvolpiatto** [comment]
Marcin S. <notifications@github.com> writes:

> It works if I run Emacs 26, but I would like to be able to run an
> older Emacs version sometimes when testing for version compatibility.

Of course, I always do this, but keep in mind that files compiled with
e.g emacs-24.5 will work on emacs-26 but the contrary will fail,
typically with your eieio error.
By chance some elisp files are working with a lower version when compiled
with a higher version but not helm and AFAIK any package using eieio.

--
Thierry
